ALTER TABLE _users ADD COLUMN first_name TEXT NOT NULL DEFAULT '';
ALTER TABLE _users ADD COLUMN last_name TEXT NOT NULL DEFAULT '';
ALTER TABLE _users ADD COLUMN phone TEXT NOT NULL DEFAULT '';
ALTER TABLE _users ADD COLUMN avatar_file_id TEXT;

-- One-time password reset tokens, generated by an admin from the dashboard
-- (see docs/api-reference.md: no SMTP is configured in v0.2, so self-service
-- "forgot password" email isn't possible yet — an admin mints a token here
-- and hands it to the user out-of-band; POST /api/auth/reset-password
-- consumes it). The token itself is the primary key: it's a high-entropy
-- random value, so no separate id column is needed.
CREATE TABLE _password_resets (
    token      TEXT PRIMARY KEY,
    user_id    TEXT NOT NULL,
    expires_at TEXT NOT NULL,
    used       INTEGER NOT NULL DEFAULT 0,
    created    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
