package auth

// Wordlist is onebox's own fixed word list for recovery phrases — BIP39-
// style (a fixed dictionary, words drawn independently at random) but not
// a claim of byte-for-byte compatibility with the canonical BIP39 English
// list, since nothing in onebox interoperates with external BIP39 tooling.
// At 750+ unique lowercase words, a 12-word phrase carries well over 100
// bits of entropy (log2(len(Wordlist)) * 12) — see TestWordlistEntropy.
var Wordlist = []string{
	"anchor", "angle", "ankle", "apple", "apron", "arch", "arctic", "arrow", "ash", "aspen",
	"autumn", "badge", "bakery", "balloon", "bamboo", "banjo", "barley", "barn", "basil", "basket",
	"beacon", "beam", "bear", "beaver", "beech", "bell", "berry", "bicycle", "birch", "bird",
	"biscuit", "blanket", "blaze", "blossom", "blue", "boat", "bolt", "bone", "book", "boot",
	"border", "bottle", "boulder", "branch", "brass", "bread", "breeze", "brick", "bridge", "bright",
	"brook", "brown", "brush", "bubble", "bucket", "buckle", "buffalo", "bugle", "bulb", "bull",
	"burrow", "butter", "button", "cabin", "cactus", "camel", "camera", "campus", "canal", "candle",
	"candy", "canoe", "canvas", "canyon", "cape", "captain", "cargo", "carpet", "carrot", "castle",
	"cattle", "cave", "cedar", "cellar", "century", "chain", "chair", "chalk", "charm", "chart",
	"cheese", "cherry", "chess", "chestnut", "chick", "chimney", "chisel", "cider", "cinder", "circle",
	"clarify", "classic", "clay", "cliff", "cloak", "clover", "cinnamon", "cloud", "coconut", "cobalt",
	"cocoa", "coffee", "coin", "colony", "comet", "compass", "concert", "coral", "cork", "corn",
	"cotton", "cottage", "cougar", "cousin", "cover", "coyote", "crab", "cradle", "crane", "crater",
	"cream", "creek", "crest", "cricket", "crimson", "crocus", "crown", "crumb", "crystal", "cub",
	"cuckoo", "cup", "curl", "current", "curtain", "custard", "cypress", "daisy", "dawn", "deck",
	"deer", "delta", "desert", "diamond", "ditch", "dolphin", "domino", "donkey", "dough", "dove",
	"dragon", "drift", "drum", "duck", "dust", "eagle", "earth", "east", "echo", "eel",
	"egret", "elbow", "elm", "ember", "emerald", "emperor", "engine", "envelope", "equator", "estate",
	"evening", "explorer", "fabric", "falcon", "farm", "fawn", "feather", "fence", "fern", "ferry",
	"fiddle", "field", "fig", "finch", "fire", "flag", "flame", "flask", "fleet", "flint",
	"flood", "flour", "flower", "flute", "foam", "fog", "forest", "forge", "fossil", "fountain",
	"fox", "frame", "freckle", "frog", "frost", "fruit", "fudge", "gable", "galaxy", "gallery",
	"garden", "garnet", "gate", "gazelle", "gecko", "gem", "geyser", "ginger", "giraffe", "glacier",
	"glade", "glass", "globe", "glove", "goat", "goblet", "gold", "goose", "gorge", "grain",
	"grape", "grass", "gravel", "green", "grotto", "grove", "guitar", "gully", "gutter", "habitat",
	"hammer", "hamster", "harbor", "hare", "harp", "harvest", "hatch", "hawk", "hazel", "heather",
	"hedge", "helmet", "heron", "hickory", "hill", "hinge", "hive", "hollow", "honey", "hoof",
	"horizon", "horn", "hornet", "horse", "hound", "hut", "hyacinth", "ice", "iceberg", "icicle",
	"igloo", "indigo", "inlet", "iris", "island", "ivory", "ivy", "jackal", "jade", "jaguar",
	"jasmine", "jelly", "jewel", "journey", "jungle", "juniper", "kangaroo", "kayak", "kelp", "kettle",
	"kingdom", "kite", "kitten", "kiwi", "knight", "knot", "koala", "ladder", "lagoon", "lake",
	"lamb", "lantern", "lark", "laurel", "lava", "lavender", "leaf", "ledge", "lemon", "lentil",
	"leopard", "lettuce", "lichen", "lilac", "lily", "lime", "linen", "lion", "lizard", "lobster",
	"lodge", "log", "lotus", "lumber", "lunar", "lynx", "magnet", "magnolia", "magpie", "maize",
	"mallow", "mango", "manor", "maple", "marble", "marigold", "market", "marsh", "meringue", "meadow",
	"melody", "melon", "mesa", "meteor", "millet", "mint", "mirror", "mist", "mitten", "moccasin",
	"mole", "monkey", "moon", "moose", "moraine", "moss", "moth", "mountain", "mouse", "mulberry",
	"museum", "mushroom", "music", "nectar", "needle", "nest", "nettle", "night", "noodle", "north",
	"nutmeg", "oak", "oasis", "oat", "ocean", "olive", "onion", "opal", "orange", "orbit",
	"orchard", "orchid", "oriole", "osprey", "ostrich", "otter", "outpost", "owl", "oxygen", "oyster",
	"paddle", "palace", "palm", "pansy", "panther", "papaya", "parade", "parcel", "parrot", "parsley",
	"pasture", "patch", "peach", "peacock", "peak", "pearl", "pebble", "pecan", "pelican", "penguin",
	"pepper", "petal", "petunia", "pheasant", "pickle", "pigeon", "pillar", "pillow", "pine", "pineapple",
	"pinecone", "pioneer", "pipe", "planet", "plateau", "platform", "plaza", "plum", "plume", "pocket",
	"pond", "poplar", "poppy", "porch", "possum", "pouch", "prairie", "pretzel", "primrose", "prism",
	"puddle", "puffin", "pumpkin", "puppy", "purple", "quail", "quartz", "quilt", "rabbit", "raccoon",
	"radish", "raft", "rail", "rainbow", "raisin", "rapids", "raven", "reef", "reindeer", "ribbon",
	"ridge", "river", "robin", "rock", "rocket", "rooster", "root", "rose", "rowan", "ruby",
	"saddle", "saffron", "sage", "sail", "salmon", "sand", "sandal", "sapling", "sapphire", "sardine",
	"savanna", "scarf", "school", "scout", "sea", "seal", "season", "seaweed", "sequoia", "shale",
	"shark", "shell", "shelter", "shepherd", "shield", "shore", "shrimp", "shrub", "silver", "skiff",
	"skunk", "sky", "sled", "sloth", "smoke", "snail", "snow", "soap", "sock", "sofa",
	"soil", "sparrow", "spice", "spider", "sponge", "spool", "spring", "spruce", "squash", "squid",
	"squirrel", "stable", "stag", "star", "starfish", "statue", "steam", "stem", "stone", "stork",
	"storm", "stream", "street", "stump", "sugar", "sultan", "summer", "summit", "sun", "sunflower",
	"swallow", "swamp", "swan", "sweater", "sycamore", "syrup", "table", "tadpole", "talon", "tangerine",
	"tavern", "temple", "terrace", "terrier", "thicket", "thistle", "thread", "thrush", "thunder", "tiger",
	"timber", "toad", "tomato", "topaz", "torch", "toucan", "tower", "trail", "trellis", "trout",
	"trumpet", "trunk", "tulip", "tundra", "tunnel", "turkey", "turnip", "turtle", "tusk", "twig",
	"umbrella", "urchin", "valley", "vanilla", "velvet", "venture", "vessel", "vine", "vineyard", "violet",
	"volcano", "voyage", "walnut", "walrus", "warbler", "wasp", "water", "weasel", "wetland", "whale",
	"wheat", "whistle", "willow", "window", "wing", "winter", "wolf", "wood", "wool", "wren",
	"yak", "yarrow", "yew", "yogurt", "zebra", "zephyr",
}
